### ISSUE TITLE
Exfalso?

### ISSUE THREAD

**Issue by felipehw** [flathub/io.github.quodlibet.QuodLibet#10]
Exfalso comes inside the `io.github.quodlibet.QuodLibet ` flatpak but I can't access this app from the Gnome Shell UI or GUI menus.

I just can access exfalso using something like `flatpak run --command=exfalso io.github.quodlibet.QuodLibet`.

There is a way to make the exfalso accessible directly from the UI *out of box*? Or I need to use `alias`, etc.?

**Comment by lazka** [comment]
The plan was to create a separate flatpak for it. We already have one upstream: https://github.com/quodlibet/quodlibet/tree/master/flatpak

**Comment by lazka** [comment]
I've created https://github.com/flathub/flathub/pull/1355

**Comment by nedrichards** [comment]
This has been merged. Will be published as soon as it's built https://github.com/flathub/io.github.quodlibet.ExFalso
