### ISSUE TITLE
Update to 4.3.0

### ISSUE THREAD

**Issue by nedrichards** [flathub/io.github.quodlibet.QuodLibet#11]
It's been out a whole 17 hours ;-) but yeah, now exfalso is up with 4.3.0 it'd be great to update here as well at your convenience.

**Comment by lazka** [comment]
I wanted to yesterday, but gitlab.com downloads were down because of a DOS attack :)

**Comment by nedrichards** [comment]
Damn you DoSers! anyway, thanks
