### ISSUE TITLE
Cannot edit tags

### ISSUE THREAD

**Issue by jahed** [flathub/io.github.quodlibet.QuodLibet#13]
When I try to edit tags for any of my tracks I get the following error:

![Screenshot from 2020-04-27 21-27-00](https://user-images.githubusercontent.com/3330963/80417587-e6330d00-88cd-11ea-8b61-2ce421ab59d9.png)

This happens to all of my tracks so it's definitely not a permission or corruption error. I've used the non-Flatpak version of QuodLibet to edit them in the past so I'm assuming it's a permissions issue. It seems QuodLibet might not have write permissions or it could be something else.

My music is stored on a separate NTFS drive under `/run/media/...`. All of them have `0777` permissions. Using QuodLibet 4.3.0, Flatpak 1.4.4 on Fedora 31.

Any help is appreciated.

Thanks.

**Comment by lazka** [comment]
Thanks, I'll try to reproduce.

**Comment by jahed** [comment]
Apologies! This issue isn't caused by this repo.

I just noticed that I can't modify files under my NTFS drive even with write permissions. For some reason it's mounted as read-only. Didn't even know that was possible and none of the interfaces in GNOME indicates that...

Turns out [Windows locks the NTFS drive even after a shutdown](https://askubuntu.com/questions/70281/why-does-my-ntfs-partition-mount-as-read-only). Something to do with Windows Update... even though the drive has no Windows-specific stuff on it.

Even on Linux, Windows haunts me. :disappointed:

**Comment by lazka** [comment]
Yeah, you have to disable fast startup under Windows when planing to work with Linux. At least for me it never switched itself back on.

Thanks for the followup. In general the flatpak version should work the same as the distro one. If you find differences please report them, thanks!
