### ISSUE TITLE
Update platform/runtime to GNOME 43

### ISSUE THREAD

**Issue by x80486** [flathub/io.github.quodlibet.QuodLibet#24]

**Comment by lazka** [comment]
Thanks, blocked on https://github.com/flathub/io.github.quodlibet.QuodLibet/pull/20#issuecomment-1078273666

The easiest fix would be to delete libsoup 3 somehow globally, or prevent it being loaded.

**Comment by 0rzech** [comment]
Would it be possible to move directly to Gnome 43?

Btw., this is what I got today (posting just for additional context):

```
Informacja: (przypięte) org.gnome.Platform//41 jest niewspierane z powodu:
   The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
Programy używające tego środowiska wykonawczego:
   io.github.quodlibet.ExFalso, io.github.quodlibet.QuodLibet
```

**Comment by 0rzech** [comment]
Would it be possible to move directly to GNOME 43? This where all other applications already are, at least on my machine.

Btw., this is what I got today (posting just for additional context):

```
Informacja: (przypięte) org.gnome.Platform//41 jest niewspierane z powodu:
   The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
Programy używające tego środowiska wykonawczego:
   io.github.quodlibet.ExFalso, io.github.quodlibet.QuodLibet
```

**Comment by 0rzech** [comment]
Would it be possible to move directly to GNOME 43? This where all other applications already are, at least on my machine.

Btw., this is what I got today (posting just for additional context):

```
Informacja: (przypięte) org.gnome.Platform//41 jest niewspierane z powodu:
   The GNOME 41 runtime is no longer supported as of September 17, 2022. Please ask your application developer to migrate to a supported platform.
Programy używające tego środowiska wykonawczego:
   io.github.quodlibet.ExFalso, io.github.quodlibet.QuodLibet
```
