### ISSUE TITLE
Cannot drag-and-drop music files to UI

### ISSUE THREAD

**Issue by ysteina** [flathub/io.github.quodlibet.QuodLibet#4]
Title sums it up. I tried to drag-and-drop some Opus files to the UI, but nothing happened. I tried it with the PPA version and it worked.

Flatpak v. 0.99.3
KDE Plasma 5.13
Latest quodlibet version

**Comment by lazka** [comment]
Looks like this is a general flatpak problem: https://github.com/flatpak/xdg-desktop-portal/issues/99

**Comment by ysteina** [comment]
Hopefully support will be implemented soon. :-)

**Comment by ysteina** [comment]
Functionality has been added in Flatpak now. Unsure in which version, but drag-and-drop now works with Flatpak 1.2.0.

**Comment by lazka** [comment]
Nice, thanks for tracking this!
