### ISSUE TITLE
QuodLibet does not respect dark theme when installed with flatpak

### ISSUE THREAD

**Issue by RoestVrijStaal** [flathub/io.github.quodlibet.QuodLibet#54]
Title says it all.

At the moment my eyes burn because Quod Libet uses a white theme instead of a black one like other flatpak applications (Flatseal, XnViewMP...)  and native Qt and GTK applications do.

Some output of `inxi -Sz`:

> Distro: MX-23.4_x64 Libretto December 15  2023
> Kernel: 6.10.12-1-liquorix-amd64
> Desktop: KDE Plasma v: 5.27.5 

> Package: flatpak
> Version: 1.14.10-1~deb12u1

> Quod Libet
> 4.6.0

Please ping me if you need more information for debugging :slightly_smiling_face:

**Comment by lazka** [comment]
Do you have any other GTK based app via flathub that respects it by any chance?

**Comment by RoestVrijStaal** [comment]
> Do you have any other GTK based app via flathub that respects it by any chance?

By judging from the source code, Flatseal seems to be founded upon the Gnome / GTK platform. 
It does respect and follow the theme of my KDE desktop environment. 
Same goes for Ferdium.

Czkawka appers to use GTK4 and also burns my eyes with its white theme. 

All the 3 apps I mentioned are installed with flatpak.

**Comment by lazka** [comment]
I see thanks. I can reproduce, also outside of flatpak, so not flatpak related.

I did a quick check, and it seems this has to be implemented in each app, so this is https://github.com/quodlibet/quodlibet/issues/4011

**Comment by RoestVrijStaal** [comment]
Ah I see.

Beat me why theme switching and/configuring needs to be a separate plugin TBH.
